# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning Python with the Leetcode Problemset
email: yasser{dot}ebrahim at geemail dot com
description: > # this means to ignore newlines until "baseurl:"
  This blog documents my road to learn Python by solving programming problems
  on leetcode.com. I will be adding a post for each problem worthy of discussion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  yebrahim

# Build settings
markdown: kramdown
